package tech.eproducts.review_rating_service.model;

// Lombok annotations for automatic generation of boilerplate code

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Document(collection = "reviews") // Specifies the MongoDB collection name
@Data // Lombok annotation to generate getters, setters, and other utility methods
@NoArgsConstructor // Generates a no-argument constructor
@AllArgsConstructor // Generates a constructor with all fields
public class Review {

    @Id // Marks this field as the primary key in the MongoDB document
    private String id;

    // Reference to the Product being reviewed
    @DBRef // Indicates that this field is a reference to another document
    private Product product; // The product associated with this review

    private String comment; // The comment text of the review
    private Integer rating; // The rating given in the review (e.g., 1 to 5)

    @CreatedDate // Automatically populated with the current date when the review is created
    private LocalDateTime createdAt;

    @LastModifiedDate // Automatically updated with the current date when the review is modified
    private LocalDateTime updatedAt;

    // Constructors, getters, and setters are generated by Lombok annotations
}