package tech.eproducts.order_management_service.model;

// Lombok annotations for automatic generation of boilerplate code

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Represents a product entity in the system.
 * This class is mapped to the "products" collection in MongoDB.
 */
@Document(collection = "products") // Specifies the MongoDB collection name
@Data // Lombok annotation to generate getters, setters, and other utility methods
@AllArgsConstructor // Generates a constructor with all fields
@NoArgsConstructor // Generates a no-argument constructor
public class Product {

    @Id // Marks this field as the primary key in the MongoDB document
    private String id; // Unique identifier for the product

    private String name; // The name of the product
    private String image; // URL or path to the product image
    private String brand; // The brand of the product
    private String category; // The category to which the product belongs
    private String description; // A brief description of the product
    private Double rating = 0.0; // The average rating of the product, initialized to 0.0
    private Integer numReviews = 0; // The number of reviews for the product, initialized to 0
    private Double price = 0.0; // The price of the product, initialized to 0.0
    private Integer countInStock = 0; // The number of items available in stock, initialized to 0

    @CreatedDate // Automatically populated with the current date when the product is created
    private LocalDateTime createdAt; // Timestamp for when the product was created

    @LastModifiedDate // Automatically updated with the current date when the product is modified
    private LocalDateTime updatedAt; // Timestamp for when the product was last updated

    // Constructors, getters, and setters are generated by Lombok annotations
}